name = "Magic and Tech"
author = "Elias"
version = "0.15.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc1feee1efec714e30971827593ca41ee40463d01e31761194278fad45bcf505"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
